error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/readinglist
    username: lmthien
    password: pass
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  profiles: cloud
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect